import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "@/lib/api/v1"; // generated by openapi-typescript
import { retrieveLaunchParams } from "@telegram-apps/sdk-react"

const fetchClient = createFetchClient<paths>({
  baseUrl: import.meta.env.VITE_API_URL,
  headers: {
    "Access-Control-Allow-Credentials": true,
    'Authorization': `tma ${retrieveLaunchParams().initDataRaw}`
  },
});
const $api = createClient(fetchClient);

export default $api;
